In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('data/sample_submission.csv')  # replace with your actual load command
df.head()

   id      DIC
0   6  2117.76
1   8  2117.76
2  12  2117.76
3  14  2117.76
4  17  2117.76

In [2]:
# Explore the dataset
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848 entries, 0 to 847
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      848 non-null    int64
 1   DIC     848 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 13.4 KB

                id           DIC
count   848.000000  8.480000e+02
mean   1996.267689  2.117760e+03
std    1226.032972  9.100314e-13
min       6.000000  2.117760e+03
25%     946.000000  2.117760e+03
50%    1900.000000  2.117760e+03
75%    3050.500000  2.117760e+03
max    4236.000000  2.117760e+03

In [3]:
# Find the percentage of missing values in each column
(df.isna().mean() * 100)

id     0.0
DIC    0.0
dtype: float64